### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by fsproru** [pivotal/cedar#259]
Hi there,

Thanks for working on cedar! It's a great BDD framework for iOS. 

Just curious, is Swift support on the horizon ? 

Alex

**Comment by dsanc89** [comment]
Hey @jeffh , just wanted to follow up on this after Swift officially went open source. Does that change anything with respect to adding this support in Cedar? -- specifically the support for full reflection on dynamic dispatch for fakes, doubles and spies to work. (or is this something that is more related to being in Quick?).

**Comment by tjarratt** [comment]
The biggest issue, as far as I see it, is that the support for interop with Objective-C++ still isn't in Swift.

It's possible to write tests with Cedar in swift, if you only expose the `it`, `describe` and `context` functions, but (afaik) there isn't a great way to use the test doubles and matchers that Cedar exposes in a pure swift context.

My current thinking is that it would be nice to be able to pull in *just* the Cedar runner as a dynamic framework for Swift. For assertions you could choose to use Nimble or even XCTest assertions.

There aren't any absolute plans right now to make Cedar's fakes and matchers usable from Swift. I'd love to learn of a way to make it work well, but so far I haven't seen anything in Swift that would make it possible.

**Comment by briancroom** [comment]
Following up on what @tjarratt was describing, I have just opened a PR for exposing the Cedar test runner to Swift (#367). I agree that making the matchers and doubles available would effectively require rewriting them given the current state of the tools.

@dsanc89 with respect to the feasibility of dynamically-generated test doubles for Swift objects, it continues to appear unlikely that such tools will be possible in the general case for the foreseeable future.

**Comment by tjarratt** [comment]
@fsproru @dsanc89 I'm going to close this issue for now, since we've just merged in @briancroom's PR to allow using the Cedar runner from Swift.

I'm going to continue thinking about Cedar's test doubles and how they fit into the big picture of testing with Swift, so I don't want this conversation to be over by any means. Please re-open this issue, or open new ones should anything change in the future re: reflection, Swift and dynamic dispatch that might make it feasible for Cedar to support Swift more fully.

**Comment by fsproru** [comment]
Thanks @tjarratt
