### ISSUE TITLE
Trying to use cedar fails with Xcode not able to find the file <memory>

### ISSUE THREAD

**Issue by codeman9** [pivotal/cedar#339]
pull from head, try to run specs target. Xcode can no longer find the < memory > file in Argument.h

**Comment by akitchen** [comment]
This depends on how you are integrating Cedar.  The TL;DR here is that addition of the dynamic iOS framework means all headers need to be imported in the library umbrella header, which exposes the C++ stuff more directly.  On master, some #imports have been reorganized in order to support this.  Any file that imports/includes C++ must also be C++

There are a few workarounds: find the related file in your codebase by expanding the compilation failure message to find your file.  Change it to Objective-C++ by adding an 'm' to its extension (Foo.mm)

If this file is your main.m and for some reason you don't want to do that, you can also use NSClassFromString(@"CedarApplicationDelegate") instead of [CedarApplicationDelegate class]

HTH

**Comment by gudatcomputers** [comment]
FWIW to future readers, this also means you'll have to remove importing Cedar from prefix headers (if you're still using those).

**Comment by idoru** [comment]
FWIW to future readers, this also means you'll have to remove importing Cedar from prefix headers (if you're still using those).

**Comment by codeman9** [comment]
Maybe it wasn't clear, my project was working fine with Cedar and I was only using Cedar .mm files as far as I was aware. All I did was pull latest HEAD and this error came up. Neither of @akitchen workarounds apply to my project.

**Comment by codeman9** [comment]
FWIW, I followed @idoru 's advice and removed the #import <Cedar/Cedar.h> from my Specs .pch file. After then importing <Cedar/Cedar.h> in all of my spec files and a few other imports here and there, the target built and ran fine. This would be a pain if I had hundreds of spec files that needed updating, luckily I only have a few right now. Is there any better way?

**Comment by pivotal-brian-croom** [comment]
Apple seems to be discouraging the use of precompiled headers in new projects, however if you are using one and would like to use it to import Cedar's umbrella header, you could try wrapping the import in a #ifdef __cplusplus / #endif block. This should result in the import only applying to your .mm files, which are being compiled in C++ mode.
