### ISSUE TITLE
Running Individual Specs

### ISSUE THREAD

**Issue by alexvbush** [pivotal/cedar#394]
Hey guys, how can I run individual specs with Cedar and not the whole test suite?

**Comment by idoru** [comment]
Hi @alexvbush,

You can do this by changing it()s to fit()

It also works for context() and describe()

As long as there is one fit/fcontext/fdescribe Cedar will only run those particular examples.

**Comment by alexvbush** [comment]
@idoru ha, interesting. So there's no way to specify what line in a spec file I want to run? I'm thinking of how rspec does it

**Comment by tooluser** [comment]
Line numbers change while you're working on a file. I think this was chosen because it's more reliable.

**Comment by tjarratt** [comment]
Agreed, fit and fdescribe and fcontext were chosen because they can be done easily while looking at code. It is also possible to write tools that easily add / remove focus (even integrating with the Xcode editor so you can do this with a keyboard shortcut). 

Do you have a strong preference for the rspec file name and line number pattern? I'm curious what you like about that system, since it's very different from Cedar (and other BDD frameworks like Gingko or Quick). 

Sent From A Very Small Keyboard

**Comment by tooluser** [comment]
I’ve been using rspec lately, pairing, and have seen at least three times this week where people weren’t testing what they thought because line numbers had changed. 

I do like RSpec’s `focus: ‘category_name’` and subsequent `rspec —focus category_name`, though. Can be handy.

Line numbers are implementation details.

**Comment by tjarratt** [comment]
How might the --focus categoryName pattern be ported to Cedar? That's a really interesting idea...

If each spec had a way of specifying it's "category" and we respected a CEDAR_FOCUS_CATEGORY env var... would that be helpful and useful?

Sent From A Very Small Keyboard

**Comment by alexvbush** [comment]
Like numbers were super useful running a spec you're looking at from vim.
The line number you're cursor is on was used to run specific test with rspec

**Comment by tooluser** [comment]
I wonder if you’ve seen cppforlife’s plugin that does exactly that, Tim? Runs the spec the cursor is in?

**Comment by tjarratt** [comment]
@tooluser yeah :)

I have been maintaining cppforlife's Xcode plugins, since he's moved on past iOS development. Now that Apple has deprecated the old, unofficial Xcode 7 plugin interface, I'm in the process of trying to port them to the Xcode 8 API (née XcodeKit).
